version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g npm@10.8.2
      - npm ci
      
  pre_build:
    commands:
      - echo "Starting build phase..."
      - node --version
      - npm --version
      
  build:
    commands:
      - echo "Building NestJS application..."
      - npm run build
      - echo "Build completed"
      
  post_build:
    commands:
      - echo "Starting post-build phase..."
      - npm ci --only=production
      - echo "Removing development files..."
      - rm -rf src/
      - rm -rf test/
      - rm -rf coverage/
      - rm -rf node_modules/.cache
      - echo "Post-build completed"

artifacts:
  files:
    - dist/**/*
    - node_modules/**/*
    - package.json
    - package-lock.json
    - ecosystem.config.js
  exclude-paths:
    - '**/*.ts'
    - '**/*.map'
    - '**/test/**'
    - '**/tests/**'
    - '**/*.md'
    - 'node_modules/**/*.txt'
  base-directory: '.'
  discard-paths: no

cache:
  paths:
    - node_modules/**/*
