version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm install
      - npm --version
      - node --version
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - if [ -f appspec.yml ]; then cp appspec.yml dist/; fi
      - mkdir -p dist/scripts
      - if [ -d scripts ]; then cp -r scripts/* dist/scripts/; fi
      - if [ -f .env ]; then cp .env dist/; fi
artifacts:
  files:
    - '**/*'
  base-directory: dist
