version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install -g @nestjs/cli
      - npm ci
      
  pre_build:
    commands:
      - echo "Running tests..."
      - npm run test
      
  build:
    commands:
      - echo "Building the NestJS application..."
      - npm run build
      - echo "Build completed successfully"
      
  post_build:
    commands:
      - echo "Preparing production dependencies..."
      - npm ci --only=production
      - echo "Post build completed"

artifacts:
  files:
    - dist/**/*
    - node_modules/**/*
    - package.json
    - package-lock.json
  discard-paths: no

cache:
  paths:
    - node_modules/**/*
