version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - npm install
      - npm --version
      - node --version
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - cp appspec.yml dist/
      - cp -r scripts dist/
      - cp .env dist/
artifacts:
  files:
    - '**/*'
  base-directory: dist
